# Generated by Django 5.2.9 on 2025-12-21 22:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("messages_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_id", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impressions",
                        to="messages_app.pulsemessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Impression",
                "verbose_name_plural": "Message Impressions",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["message", "app_id", "timestamp"],
                        name="analytics_m_message_0b600f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageTap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_id", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taps",
                        to="messages_app.pulsemessage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Tap",
                "verbose_name_plural": "Message Taps",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["message", "app_id", "timestamp"],
                        name="analytics_m_message_ff20f8_idx",
                    )
                ],
            },
        ),
    ]
