# Generated by Django 5.2.9 on 2025-12-28 12:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique identifier for the key (e.g., 'brightdata_api_key')", max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Name must start with lowercase letter, contain only lowercase letters, numbers, and underscores', regex='^[a-z][a-z0-9_]*$')])),
                ('service_name', models.CharField(blank=True, help_text="Third-party service name (e.g., 'Brightdata')", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Purpose and usage notes for this API key')),
                ('encrypted_value', models.TextField(help_text='The encrypted API key value')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive keys will not be returned by the API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, help_text='Last time this key was retrieved via API', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'is_active'], name='api_keys_ap_name_fe0daa_idx')],
            },
        ),
    ]
