# Generated by Django 5.2.9 on 2025-12-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_keys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text="Optional expiration date. Leave blank for keys that don't expire.", null=True),
        ),
    ]
