# Generated by Django 5.2.9 on 2025-12-21 22:01

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TargetApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "app_id",
                    models.CharField(
                        help_text="Unique identifier (e.g., 'brighton', 'edinburgh')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "app_name",
                    models.CharField(
                        help_text="Display name (e.g., 'The Brighton App')",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Target App",
                "verbose_name_plural": "Target Apps",
                "ordering": ["app_name"],
            },
        ),
        migrations.CreateModel(
            name="PulseMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Main heading of the message (3-100 chars)",
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Message body content (max 1000 chars)",
                        validators=[django.core.validators.MaxLengthValidator(1000)],
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="Optional image URL to display",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "cta_text",
                    models.CharField(
                        blank=True,
                        help_text="Button text (e.g., 'Learn More', 'Open')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "cta_action",
                    models.CharField(
                        blank=True,
                        help_text="Action URL or deep link (e.g., 'https://...' or 'app://events/123')",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("modal", "Modal - Centered Popup"),
                            ("banner", "Banner - Top/Bottom Bar"),
                            ("bottom_sheet", "Bottom Sheet - Slides Up"),
                            ("full_screen", "Full Screen - Takeover"),
                        ],
                        default="modal",
                        max_length=20,
                    ),
                ),
                (
                    "banner_position",
                    models.CharField(
                        choices=[
                            ("top", "Top of Screen"),
                            ("bottom", "Bottom of Screen"),
                        ],
                        default="top",
                        help_text="Only applies to banner type messages",
                        max_length=10,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Critical - Show Immediately"),
                            (2, "High - Show Soon"),
                            (3, "Normal - Standard Queue"),
                            (4, "Low - Background"),
                        ],
                        default=3,
                    ),
                ),
                (
                    "is_dismissible",
                    models.BooleanField(
                        default=True, help_text="Can users dismiss this message?"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When to start showing the message",
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to stop showing (leave blank for no end)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Enable to make message live"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_apps",
                    models.ManyToManyField(
                        help_text="Which apps should show this message",
                        related_name="messages",
                        to="messages_app.targetapp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pulse Message",
                "verbose_name_plural": "Pulse Messages",
                "ordering": ["priority", "-start_date"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "start_date", "end_date"],
                        name="messages_ap_is_acti_5569e5_idx",
                    ),
                    models.Index(
                        fields=["message_type"], name="messages_ap_message_536e3d_idx"
                    ),
                ],
            },
        ),
    ]
