# Generated by Django 5.2.9 on 2025-12-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulsemessage',
            name='background_color',
            field=models.CharField(blank=True, default='', help_text='Background color (hex like #FF5733 or leave empty for default)', max_length=20),
        ),
        migrations.AddField(
            model_name='pulsemessage',
            name='body_color',
            field=models.CharField(blank=True, default='', help_text='Body text color (hex like #FF5733 or leave empty for default)', max_length=20),
        ),
        migrations.AddField(
            model_name='pulsemessage',
            name='button_color',
            field=models.CharField(blank=True, default='', help_text='Button/CTA color (hex like #FF5733 or leave empty for default)', max_length=20),
        ),
        migrations.AddField(
            model_name='pulsemessage',
            name='title_color',
            field=models.CharField(blank=True, default='', help_text='Title text color (hex like #FF5733 or leave empty for default)', max_length=20),
        ),
    ]
