# Generated by Django 5.1.2

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0002_add_styling_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulsemessage',
            name='background_color',
            field=models.CharField(blank=True, default='', help_text='Hex color like #FF5733', max_length=20, verbose_name='Background'),
        ),
        migrations.AlterField(
            model_name='pulsemessage',
            name='body',
            field=models.TextField(help_text='Message body content (max 1000 chars)', validators=[django.core.validators.MaxLengthValidator(1000)], verbose_name='Body (15px)'),
        ),
        migrations.AlterField(
            model_name='pulsemessage',
            name='body_color',
            field=models.CharField(blank=True, default='', help_text='Hex color like #FF5733', max_length=20, verbose_name='Body Color'),
        ),
        migrations.AlterField(
            model_name='pulsemessage',
            name='button_color',
            field=models.CharField(blank=True, default='', help_text='Hex color like #FF5733', max_length=20, verbose_name='Button Color'),
        ),
        migrations.AlterField(
            model_name='pulsemessage',
            name='title',
            field=models.CharField(help_text='Main heading of the message (3-100 chars)', max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Title (20px Bold)'),
        ),
        migrations.AlterField(
            model_name='pulsemessage',
            name='title_color',
            field=models.CharField(blank=True, default='', help_text='Hex color like #FF5733', max_length=20, verbose_name='Title Color'),
        ),
    ]
