# Generated by Django 5.2.9 on 2025-12-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0003_alter_pulsemessage_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pulsemessage',
            name='button_text_color',
            field=models.CharField(blank=True, default='', help_text='Button text color', max_length=20, verbose_name='Button Text'),
        ),
        migrations.AlterField(
            model_name='pulsemessage',
            name='button_color',
            field=models.CharField(blank=True, default='', help_text='Button background color', max_length=20, verbose_name='Button Color'),
        ),
    ]
